# This is a basic workflow to help you get started with Actions

name: Scrape BNT

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '50 6,9,13,17 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env: 
            MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          pip3 install requests pymongo dnspython beautifulSoup4 ipython nbformat feedparser  python-dateutil
          ipython -c "%run scrape_bnt.ipynb"
